[project]
name = "rdf-graph-visualization"
version = "0.1.0"
description = "Visualization of RDF graphs in Turtle format in 3D on the web."
keywords = ["rdf", "graph", "turtle", "visualization"]
license = "MIT"
repository = "https://github.com/Materials-Data-Science-and-Informatics/rdf-graph-visualization"
homepage = "https://github.com/Materials-Data-Science-and-Informatics/rdf-graph-visualization"

[[project.people]]
family-names = "Soylu"
given-names = "Mustafa"
email = "m.soylu@fz-juelich.de"
orcid = "https://orcid.org/0000-0003-2637-0432"
contribution = "The main author, maintainer and tester."
contribution_begin = "2023-03-01"
contribution_types = ["ideas", "code", "design", "test"]
author = true
maintainer = true

[[project.people]]
family-names = "Fathalla"
given-names = "Said"
email = "s.fathalla@fz-juelich.de"
orcid = "https://orcid.org/0000-0002-2818-5890"

contribution_begin = "2023-03-01"
contribution_types = ["ideas", "userTesting"]

[[project.people]]
family-names = "Hofmann"
given-names = "Volker"
email = "v.hofmann@fz-juelich.de"
orcid = "https://orcid.org/0000-0002-5149-603X"

contribution = "Discussions and suggestions concerning tool scope and usability."
contribution_begin = "2023-06-01"
contribution_end = "2023-06-30"
contribution_types = ["ideas", "userTesting"]
publication_author = true

[[project.people]]
family-names = "Sandfeld"
given-names = "Stefan"
email = "s.sandfeld@fz-juelich.de"
orcid = "https://orcid.org/0000-0001-9560-4728"

contribution_types = ["fundingFinding"]
publication_author = true
